# Generated by Django 5.2.6 on 2025-10-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speska',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
