# Generated by Django 5.2.6 on 2025-10-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_speska_is_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
